# Nome da GitHub Action
name: Generate GitHub Snake

# Controles de quando a automação vai rodar
on:
  # Roda automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você rode essa automação manualmente pela aba Actions
  workflow_dispatch:

# O que a automação vai fazer
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # O ID do seu usuário no GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de arquivos de saída
          # O primeiro gera a animação em SVG, o segundo em GIF para compatibilidade
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=9370DB
        env:
          # Token de acesso do GitHub, necessário para ler suas contribuições
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Envia os arquivos gerados de volta para o seu repositório
      - run: git status
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
