name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *" # Executa a cada 24 horas
  workflow_dispatch: # Permite acionamento manual
  push:
    branches:
      - master # Aciona em push para a branch master

jobs:
  generate:
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    timeout-minutes: 5 

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }} 
          outputs: github-snake.svg?color_snake=#9370DB&color_dots=#161B22,#905590,#714371,#523152,#3E243E

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
